version: '3'
services:
  rickroll:
    container_name: rickroll
    image: donswanson/rickroll:latest
    restart: unless-stopped
    ports:
      - '8080:80'
  
    healthcheck:
      test: curl --fail http://localhost/ || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s